// login action
export const HANDLE_LOGIN = 'HANDLE_LOGIN';
export const HANDLE_LOGIN_SUCCESS = 'HANDLE_LOGIN_SUCCESS';


// fetch schools
export const HANDLE_FETCH_SCHOOLS = 'HANDLE_FETCH_SCHOOLS';
export const HANDLE_FETCH_SCHOOLS_SUCCESS = 'HANDLE_FETCH_SCHOOLS_SUCCESS';


// fetch students
export const HANDLE_FETCH_STUDENTS = 'HANDLE_FETCH_STUDENTS';
export const HANDLE_FETCH_STUDENTS_SUCCESS = 'HANDLE_FETCH_STUDENTS_SUCCESS';


// fetch classes
export const HANDLE_FETCH_CLASSES = 'HANDLE_FETCH_CLASSES';
export const HANDLE_FETCH_CLASSES_SUCCESS = 'HANDLE_FETCH_CLASSES_SUCCESS';
